export const DELIVERY_TYPE = ["BY_DELIVERY", "ON_COFFEESHOP"];
export const MEMBERSHIP_TYPE = ["NEW", "ROYAL", "GOLDEN"];
export const ORDER_STATUS = [
  "SHIPPING",
  "PROCESSING",
  "DELIVERED",
  "CANCELLED",
];
export const PRODUCT_STATUS = ["BEST SELLER", "LIMITED EDITION", "DELIVERABLE"];
